name: Release

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches: [master]

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  infrastructure:
    name: Infrastructure
    runs-on: aws-sam
    env:
      AWS_SERVERLESS_BUCKET: coralogix-serverless-repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        working-directory: infra/
        run: terragrunt init

      - name: Validate
        working-directory: infra/
        run: terragrunt validate

      - name: Apply
        working-directory: infra/
        run: |
          terragrunt apply \
            -var="s3_bucket_name_prefix=${{ env.AWS_SERVERLESS_BUCKET }}" \
            -auto-approve

  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-changed-packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get Changed Packages
        id: get-changed-packages
        run: |
          export PACKAGES=$(git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha || 'origin/master' }} ${{ github.sha }} src/ | xargs -n1 dirname | sed -r 's/src\/([^\/]+).*$/src\/\1/g' | xargs -n1 basename | sort | uniq | jq -rcnR '[inputs]')
          echo "::set-output name=packages::$PACKAGES"
          echo $PACKAGES ; $packages

  validate:
    name: Validate
    runs-on: aws-sam
    needs: check
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.check.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        working-directory: src/${{ matrix.package }}
        run: sam validate
  build:
    name: Build
    runs-on: aws-sam
    env:
      AWS_SERVERLESS_BUCKET: coralogix-serverless-repo
    needs: [check, validate]
    strategy:
      matrix:
        package: ${{ fromJSON(needs.check.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
