on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: 'archive-reader'
            path: 'src/archive-reader/**'
          - name: 'athena-s3'
            path: 'src/athena-s3/**'
          - name: 'cloudtrail'
            path: 'src/cloudtrail/**'
          - name: 'cloudtrail-sns'
            path: 'src/cloudtrail-sns/**'
          - name: 'cloudwatch-logs'
            path: 'src/cloudwatch-logs/**'
          - name: 'cloudwatch-metrics'
            path: 'src/cloudwatch-metrics/**'
          - name: 'elasticsearch-reporter'
            path: 'src/elasticsearch-reporter/**'
          - name: 'kafka'
            path: 'src/kafka/**'
          - name: 'kinesis'
            path: 'src/kinesis/**'
          - name: 'lambda-extension'
            path: 'src/lambda-extension/**'
          - name: 'lambda-manager'
            path: 'src/lambda-manager/**'
          - name: 'lambda-secretLayer'
            path: 'src/lambda-secretLayer/**'
          - name: 'mongodb-atlas'
            path: 'src/mongodb-atlas/**'
          - name: 'msk'
            path: 'src/msk/**'
          - name: 'resource-metadata'
            path: 'src/resource-metadata/**'
          - name: 'resource-tags'
            path: 'src/resource-tags/**'
          - name: 's3'
            path: 'src/s3/**'
          - name: 's3-sns'
            path: 'src/s3-sns/**'
          - name: 'sf-eventlog'
            path: 'src/sf-eventlog/**'
          - name: 'sns'
            path: 'src/sns/**'
          - name: 'vpc-flow-logs'
            path: 'src/vpc-flow-logs/**'
          
          # Add more applications here...
    steps:
      - uses: actions/checkout@v2
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            '${{ matrix.app.name }}':
              - '${{ matrix.app.path }}'
      - if: steps.changes.outputs[matrix.app.name] == 'true'
        name: ${{ matrix.app.name }} Build
        run: echo ${{ matrix.app.name }}
          
      - if: steps.changes.outputs[matrix.app.name] == 'true'          
      - name: Change template and README to CF
        run: |
          chmod +x replace_codeuri.sh
          ./replace_codeuri.sh src/${{ matrix.package }}/template.* ${{ matrix.package }} src/${{ matrix.package }}/README.md
    
      - if: steps.changes.outputs[matrix.app.name] == 'true'    
      - name: Upload template file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-template
          path: src/${{ matrix.package }}/template.*
      
      - if: steps.changes.outputs[matrix.app.name] == 'true'      
      - name: Upload README file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package }}-README
          path: src/${{ matrix.package }}/README.md
          
      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: guyrenny/cloudformation-coralogix-aws
          token: ${{ secrets.DESTINATION_REPO_TOKEN }}
       
      - if: steps.changes.outputs[matrix.app.name] == 'true'      
      - name: Download template file
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.package }}-template
          
      - if: steps.changes.outputs[matrix.app.name] == 'true'          
      - name: Download README file
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.package }}-README
        
      - if: steps.changes.outputs[matrix.app.name] == 'true'        
      - name: Commit and push changes
        run: |
          if test -e "aws-integrations/lambda-integrations/${{ matrix.package }}" || test -e "aws-integrations/${{ matrix.package }}" ; then
            if test -e "aws-integrations/lambda-integrations/${{ matrix.package }}"; then
              ls
              mv template.* aws-integrations/lambda-integrations/${{ matrix.package }}/
              mv README.md aws-integrations/lambda-integrations/${{ matrix.package }}/
            else
              mv template.* aws-integrations/lambda-integrations/${{ matrix.package }}/
            fi
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout master
            git pull
            git add .
            git commit -m "Copy file from serverless repository"
            git push origin HEAD:master -f
          fi
